### ISSUE TITLE
Bug list made by Andrei :)

### ISSUE THREAD

**Issue by twisterz** [Kujiku/Clash#2]
1. Ganoderma and titan should spawn where they supose to spawn not random and make them give drop because now you kill them and you get nothin.
2. Suggestion for VIP: for those who will buy vip should have some better privileages from my opinion because you want 20$ for it (it`s more than ofiicial wtf), so you can make dbs,mets,expballs to be auto looted (to go directly into inventory) and elite,supers tho, add some vip remote WH.
3. Drop rates: since last patch the +1`s drop got lowered drastically so my opinion either you make it however you want to make but let it somehow not change it always with every patch.
4.Mobs spawn: at first mob spawn was more than perfect now you made it too low so please if you can increase them a lil more will be perfect.
5. Level up: when I first got here the levelup was when you was reaching 20% now you need 100%...no offence but this is not kinda cool because there were ppl who got 130 fast and for those who just came ain`t fair so i will let this topic at ur choice if you gonna change it how it used to be.
6. Weapon prof: there is a lil problem/bug with this wep prof coz i`m stuck at lvl 6 wep prof for 2 days now ^^ ...so if you can please fix it will be perfect.
7.Weapon prof by expballs:  if you can make the wep prof increase with expballs to be a lil lowered will be damn good because like this it takes way too manny expballs and it`s a waste.
8. Online time points: before the ``patch`` was 10 points mb,cw... now it`s double how it was...no offence but don`t you think double it just like this is kinda unfair for others who will come? At least make 13-15 points or make it back to normal (ur choice here). 
9.New character: now when you create a new acc you get 1 free exp ball, well this seems kinda uncovenient because you can create one and delete and create again and make alot of exp balls and make lvl. So it will be better if they will be get only from hunting.
10. those who want to buy vip they won`t untill they will see some good improvements to server and some good benefits from vip features. For example i can`t donate for something that even a normal player can get, and get something just like I donate 20$ for nothin.

**Comment by Cecko11** [comment]
I totally agree with everything especially with lvl up on 100% is bit stupid .. a lot of players used that lvl up on 20% and they are 130lvls now and we are not and its not that easy to get 130 lvl 
having exp ball from new char is pretty stupid you can deleting and creating and you can make 30 exp balls in 10minutes time 
donators must have something which other players cant have. the example of auto looting is excellent 
GM / PM must change something , i really like this server and literally im ready to donate 
cheers ! best regards

**Comment by Kujiku** [comment]
Nice list , i've to do it as soon as possible

**Comment by Kujiku** [comment]
You will see it live next maintenance
