### ISSUE TITLE
Bugs/suggestions

### ISSUE THREAD

**Issue by kevinsilva1995** [Kujiku/Clash#6]
Bugs: In Bird Island I noticed that when Birdmen die, some of them stay behind and block your path and/or items.

Second bug That I Found is, the bridge that crosses over to Poltergeists. It is impossible to cross over that bridge.

Third bug is, even when on capture or peace i can hit someone using scatter.

Another bug is events don't give you any rewards upon completion

Finally, I found that even if I have a db in my inventory, i am not able to dye my armor black.

Suggestions: Bring back old bosses with same rewards as before or different rewards.

Less super equipment, more +1 equipment drops.

Speed arrow amount back to 2000, so we don't have a cluster fuck of arrows taking up a lot of space in our inventories.

Online reward shop prices are way to high, lower it by at least 25%.

Add coordinates and an effect when dbs, mets, +1 items and supers end up dropping.

These are some stuff i can think of at the moment.

**Comment by kevinsilva1995** [comment]
Same thing happens in Ape City, with the monsters corpses staying behind and blocking items.

**Comment by Kujiku** [comment]
Thanks for you time , i've put it in my list you will see it live next maintenance
