### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ganicus123** [Kujiku/Clash#7]
You can not wear a black suit
my archer does not enter the game, the ID is Ganicus
no ncp that puts the items in +1
you can not claim the guard when you are reborn for the first time
It would be good cps in the game and the second reborn
there is not the person who opens the socalo to arms

**Comment by Kujiku** [comment]
@ganicus123 why you can't login with archer ? i see it work well

**Comment by Kujiku** [comment]
I've fixed it next maintenance you will see it live ;)
